version: "3.9"

services:
  floci-az:
    image: floci/floci-az:latest
    container_name: floci-az
    ports:
      - "4577:4577"
    volumes:
      - ./azure-data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - floci-net

  floci-gcp:
    image: floci/floci-gcp:latest
    container_name: floci-gcp
    ports:
      - "4588:4588"
    volumes:
      - ./gcp-data:/app/data
    networks:
      - floci-net

networks:
  floci-net:
    driver: bridge
